[theme]
primaryColor = "#087E83"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182C42"
font = "sans serif"

[server]
maxUploadSize = 30

[browser]
gatherUsageStats = false
